version: '2.17.2'
name: jimdemo # Имя проекта

services:
  php:
    container_name: jimdemo-php # Здесь и далее - имя контейнера
    build:
      context: ./php # Путь к папке, которая будет корнем сборки и где лежит Dockerfile, по которому будет собираться контейнер
    restart: unless-stopped
    # Здесь и далее - соответствие файлов и папок хоста и контейнера. Слева хост, справа контейнер. Для каждого контейнера свой маунт.
    volumes:
      - ../backend-app:/var/www # Сейчас соответствует WORKDIR в Dockerfile контейнера
      - ./php/php.ini:/usr/local/etc/php/php.ini # Подключаем php.ini куда нужно
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    container_name: jimdemo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../backend-app:/var/www # Сейчас соответствует корню домена в конфиге nginx
      - ./nginx:/etc/nginx/conf.d # Подцепляем конфиг nginx
    depends_on:
      - php
    networks:
      - internal

networks:
  internal:
    driver: bridge